FROM debian:buster-slim
RUN mkdir /app

COPY ./target-release/mailtutan /app/server

WORKDIR /app
ENTRYPOINT ["/bin/sh", "-c", "/app/server --smtp-relay-server $SMTP_SERVER --smtp-relay-server-username $SMTP_USER --smtp-relay-server-password $SMTP_PASS --smtp-auth-username $SMTP_LOGIN_USER --smtp-auth-password $SMTP_AUTH_PASS"]