name: Build and Deploy to Self Cloud

on:
  push:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use cache
      id: cache-rust
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        path: |
          /home/runner/.cargo
          /home/runner/work/tvmate/tvmate/target
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
            
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu pkg-config libssl-dev

    - name: Add aarch64
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build
      run: cross build --release --target aarch64-unknown-linux-gnu
    
    - name: List
      run: ls -la target/aarch64-unknown-linux-gnu/release
    - name: pwd
      run: pwd
    - name: List file
      run: ls -l /home/runner/work/mailtutan/mailtutan/target/aarch64-unknown-linux-gnu/release/mailtutan
    - name: perm
      run: chmod 777 /home/runner/work/mailtutan/mailtutan/target/aarch64-unknown-linux-gnu/release/mailtutan
    - name: own
      run: chown runner:runner /home/runner/work/mailtutan/mailtutan/target/aarch64-unknown-linux-gnu/release/mailtutan
    - name: List file
      run: ls -l /home/runner/work/mailtutan/mailtutan/target/aarch64-unknown-linux-gnu/release/mailtutan
    - name: Build and push
      run: docker buildx build --platform linux/arm64 -f Dockerfile.arm64 -t mailrelay:tag .

    - name: Compress image
      run: gzip mailrelay.tar

    - name: Push To SelfCloud
      run: |
        curl --location --fail --show-error 'https://bigcloud.deepwith.in/cloud/image/push' --form 'project_id="deb1901d-d809-407a-beb5-a7f679923d94"' --form "token=$SELFCLOUD_TOKEN" --form 'image=@"mailrelay.tar.gz"'
      env:
        SELFCLOUD_TOKEN: ${{ secrets.BIGCLOUD_TOKEN }}